name: Changelog CI

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
